# Generated by Django 3.1 on 2020-08-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('package', models.IntegerField(db_column='package', db_index=True, max_length=5, primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='text', max_length=40)),
                ('first_pic', models.CharField(db_column='first_pic', max_length=100)),
                ('available', models.BooleanField(db_column='available')),
            ],
            options={
                'db_table': 'Pic',
                'ordering': ['package'],
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(db_column='package', db_index=True, max_length=5)),
                ('photo', models.CharField(db_column='photo', max_length=100)),
            ],
            options={
                'db_table': 'Pics',
                'ordering': ['package'],
            },
        ),
    ]
