# Generated by Django 3.1 on 2020-08-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='available',
            field=models.BooleanField(db_column='available', default=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='package',
            field=models.IntegerField(db_column='package', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pics',
            name='package',
            field=models.IntegerField(db_column='package', db_index=True),
        ),
    ]
